_target_: dgrag.kg_construction.ner_model.LLMNERModel
llm_api: openai
model_name_or_path: deepseek-ai/DeepSeek-V3.2
base_url: https://api.siliconflow.cn/v1
api_key_env: SILICONFLOW_API_KEY
max_tokens: 300
